### ISSUE TITLE
Improve error messages for or parsing of empty columns bindings

### ISSUE THREAD

**Issue by theduncanclark** [kiln/flourish-sdk#7] opened 2017-06-06 10:25 UTC
To specify an empty columns binding you need to use quote marks. If you don't, the SDK just says your binding is invalid. We should probably try to detect what has happened and alert the user accordingly.

**Comment by robinhouston** [comment] 2017-06-06 11:22
Migrated from kiln/flourish#241

**Comment by robinhouston** [comment] 2017-06-06 11:42
This is referring to a binding such as:

    columns: "Table name::"

which is invalid without the quotes since a trailing colon has special meaning to YAML.

**Comment by robinhouston** [comment] 2017-06-15 18:51
When I try this, the error message is pretty explicit:
```
😱  Failed to parse template.yml: incomplete explicit mapping pair; a key node is missed at line 144, column 34:
        columns: Table name::
```

@theduncanclark Can you reproduce “the SDK just says your binding is invalid”?

**Comment by robinhouston** [comment] 2017-06-15 18:54
I think it would be hard to detect this situation explicitly, since the input is not valid YAML so we can’t parse it at all, unless we write our own YAML parser specially.

I’ll close this for now. We can reopen it if there’s another problem I’m not aware of.

**Closed by robinhouston** 2017-06-15 18:54 UTC

**Comment by theduncanclark** [comment] 2017-06-22 14:06
Can't reproduce this now. Maybe I was running an older version of the SDK.
